# Generated by Django 6.0.3 on 2026-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Главная'), ('menu', 'Меню'), ('contacts', 'Контакты'), ('about', 'О нас')], default='home', max_length=50, verbose_name='Страница')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок баннера')),
                ('subtitle', models.CharField(max_length=250, verbose_name='Подзаголовок баннера')),
                ('description', models.TextField(max_length=500, verbose_name='Описание баннера')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение баннера')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название сайта')),
                ('description', models.TextField(max_length=500, verbose_name='Описание сайта')),
                ('facebook', models.URLField(max_length=250, verbose_name='Ссылка на Facebook')),
                ('instagram', models.URLField(max_length=250, verbose_name='Ссылка на Instagram')),
                ('tikTok', models.URLField(max_length=250, verbose_name='Ссылка на TikTok')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('map_link', models.URLField(max_length=250, verbose_name='Ссылка на карту')),
                ('phone_number', models.CharField(max_length=250, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=250, verbose_name='Электронная почта')),
                ('working_hours', models.CharField(max_length=250, verbose_name='Часы работы')),
            ],
            options={
                'verbose_name': 'Основные настройки',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
    ]
