# Generated by Django 6.0.3 on 2026-05-07 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Используется для фильтрации. Заполняется автоматически из названия (латиницей).', max_length=100, unique=True, verbose_name='Slug (для фильтра на сайте)')),
            ],
            options={
                'verbose_name': '06) Категории',
                'verbose_name_plural': '06) Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя отправителя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('completed', 'Завершено')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
            ],
            options={
                'verbose_name': '10) Сообщения',
                'verbose_name_plural': '10) Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок (название локации или события)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '08) Галерея',
                'verbose_name_plural': '08) Галерея',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок новости')),
                ('description', models.TextField(verbose_name='Описание новости')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Изображение (16:9)')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('promotion_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания акции')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': '04) Новости',
                'verbose_name_plural': '04) Новости',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OurHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='history_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': '02) История',
                'verbose_name_plural': '02) История',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('guests', models.IntegerField(verbose_name='Количество гостей')),
                ('occasion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Повод')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': '09) Бронирования',
                'verbose_name_plural': '09) Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название сайта')),
                ('description', models.TextField(max_length=500, verbose_name='Описание сайта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Логотип сайта')),
                ('favicon', models.ImageField(blank=True, help_text='Изображение для иконки сайта (например, .ico, .png). Рекомендуется 32x32 или 64x64 пикселя.', null=True, upload_to='settings/', verbose_name='Фавикон (иконка сайта)')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Фон главного экрана')),
                ('facebook', models.URLField(max_length=250, verbose_name='Ссылка на Facebook')),
                ('instagram', models.URLField(max_length=250, verbose_name='Ссылка на Instagram')),
                ('tikTok', models.URLField(max_length=250, verbose_name='Ссылка на TikTok')),
                ('whatsapp', models.CharField(blank=True, help_text="Введите номер без '+' и пробелов, например: 996555212293", max_length=250, null=True, verbose_name='Номер WhatsApp')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('map_link', models.TextField(help_text='Используйте только атрибут src из кода вставки Google Maps (начинается с https://www.google.com/maps/embed...)', verbose_name='Ссылка на карту (iframe src)')),
                ('phone_number', models.CharField(max_length=250, verbose_name='Телефон')),
                ('delivery_phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер для доставки')),
                ('email', models.EmailField(max_length=250, verbose_name='Электронная почта')),
                ('working_hours', models.TextField(max_length=500, verbose_name='Часы работы')),
            ],
            options={
                'verbose_name': '01) Основные настройки',
                'verbose_name_plural': '01) Основные настройки',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название показателя')),
                ('value', models.CharField(max_length=50, verbose_name='Значение (например, 50+)')),
                ('icon', models.CharField(help_text='Используйте fa-solid для обычных иконок (напр. fa-solid fa-bowl-food) или fa-brands для соцсетей. Поиск: fontawesome.com/search?m=free', max_length=100, verbose_name='Иконка (FontAwesome класс)')),
            ],
            options={
                'verbose_name': '03) Статистика',
                'verbose_name_plural': '03) Статистика',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Рейтинг (1-5)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Отображать на главной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': '05) Отзывы',
                'verbose_name_plural': '05) Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название блюда')),
                ('description', models.TextField(max_length=100, verbose_name='Описание блюда')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='dish_images/', verbose_name='Изображение блюда')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Отображать на главной странице')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новое')),
                ('is_promotion', models.BooleanField(default=False, verbose_name='Акция')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена по акции')),
                ('new_until_date', models.DateField(blank=True, help_text="Блюдо будет отображаться как 'Новое' до этой даты.", null=True, verbose_name='Новое до даты')),
                ('promotion_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания акции')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='settings.category', verbose_name='Категория блюда')),
            ],
            options={
                'verbose_name': '07) Блюда',
                'verbose_name_plural': '07) Блюда',
            },
        ),
        migrations.CreateModel(
            name='HistoryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Заголовок особенности')),
                ('description', models.CharField(max_length=250, verbose_name='Описание особенности')),
                ('icon', models.CharField(help_text='Для обычных: fa-solid fa-leaf. Для брендов: fa-brands fa-bluetooth. Поиск free иконок на fontawesome.com', max_length=100, verbose_name='Иконка (FontAwesome)')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='settings.ourhistory', verbose_name='История')),
            ],
            options={
                'verbose_name': 'Особенность истории',
                'verbose_name_plural': 'Особенности истории',
            },
        ),
    ]
