# Generated by Django 6.0.3 on 2026-04-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название показателя')),
                ('value', models.CharField(max_length=50, verbose_name='Значение (например, 500+)')),
                ('icon', models.CharField(help_text='Например: fas fa-utensils', max_length=50, verbose_name='Иконка FontAwesome')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Блок статистики',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Фото клиента')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Рейтинг (1-5)')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
