# Generated by Django 6.0.3 on 2026-04-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_statistic_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon',
            field=models.CharField(max_length=100, verbose_name='Иконка (FontAwesome класс)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Значение (например: 50+ или 10k)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Фото гостя'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя гостя'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Рейтинг'),
        ),
    ]
