# Generated by Django 6.0.3 on 2026-04-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_statistic_options_alter_statistic_icon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
