# Generated by Django 6.0.3 on 2026-04-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_delete_banner_delete_statistic_delete_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='map_link',
            field=models.TextField(verbose_name='Ссылка на карту (iframe src)'),
        ),
    ]
