# Generated by Django 6.0.3 on 2026-04-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_ouradvantages_ourhistory_populardishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название показателя')),
                ('value', models.CharField(max_length=50, verbose_name='Значение (например, 50+)')),
                ('icon', models.CharField(help_text='Например: fas fa-utensils', max_length=100, verbose_name='Иконка (FontAwesome класс)')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Блок статистики',
            },
        ),
        migrations.DeleteModel(
            name='Ouradvantages',
        ),
    ]
