# Generated by Django 6.0.3 on 2026-04-25 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_statistic_delete_ouradvantages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourhistory',
            options={'verbose_name': 'Наша история', 'verbose_name_plural': 'Наша история'},
        ),
    ]
