# Generated by Django 6.0.3 on 2026-04-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_ourhistory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок особенности')),
                ('description', models.CharField(max_length=250, verbose_name='Описание особенности')),
                ('icon', models.CharField(help_text='Например: fas fa-scroll', max_length=100, verbose_name='Иконка (FontAwesome)')),
            ],
            options={
                'verbose_name': 'Особенность истории',
                'verbose_name_plural': 'Особенности истории',
            },
        ),
        migrations.RemoveField(
            model_name='ourhistory',
            name='peculiarity',
        ),
        migrations.RemoveField(
            model_name='ourhistory',
            name='title_2',
        ),
    ]
