# Generated by Django 6.0.3 on 2026-04-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_historyfeature_remove_ourhistory_peculiarity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок новости')),
                ('description', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Изображение (16:9)')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date'],
            },
        ),
    ]
