# Generated by Django 6.0.3 on 2026-04-25 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyfeature',
            name='history',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='settings.ourhistory', verbose_name='История'),
            preserve_default=False,
        ),
    ]
