# Generated by Django 6.0.3 on 2026-04-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_historyfeature_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='popular_dishes_images/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('category', models.CharField(choices=[('appetizers', 'Закуски'), ('soups', 'Супы'), ('main', 'Горячее'), ('desserts', 'Десерты'), ('drinks', 'Напитки')], max_length=50, verbose_name='Категория')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярное (на главную)')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Меню (Блюда)',
            },
        ),
        migrations.DeleteModel(
            name='PopularDishes',
        ),
    ]
