# Generated by Django 6.0.3 on 2026-04-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_dish_delete_populardishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyfeature',
            name='icon',
            field=models.CharField(help_text='Например: fa-solid fa-scroll', max_length=100, verbose_name='Иконка (FontAwesome)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon',
            field=models.CharField(help_text='Например: fa-solid fa-utensils', max_length=100, verbose_name='Иконка (FontAwesome класс)'),
        ),
    ]
