# Generated by Django 6.0.3 on 2026-04-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_alter_historyfeature_icon_alter_statistic_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyfeature',
            name='icon',
            field=models.CharField(help_text='Пример: fa-solid fa-scroll. Список на fontawesome.com', max_length=100, verbose_name='Иконка (FontAwesome)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon',
            field=models.CharField(help_text='Ищите названия на fontawesome.com/search?m=free. Пример: fa-solid fa-utensils', max_length=100, verbose_name='Иконка (FontAwesome класс)'),
        ),
    ]
