# Generated by Django 6.0.3 on 2026-04-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_alter_historyfeature_icon_alter_statistic_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyfeature',
            name='icon',
            field=models.CharField(help_text='Ищите названия на fontawesome.com/search?m=free. Используйте полный класс, например: fa-solid fa-scroll', max_length=100, verbose_name='Иконка (FontAwesome)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon',
            field=models.CharField(help_text='Ищите названия на fontawesome.com/search?m=free. Используйте полный класс, например: fa-solid fa-utensils', max_length=100, verbose_name='Иконка (FontAwesome класс)'),
        ),
    ]
