# Generated by Django 6.0.3 on 2026-04-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_alter_historyfeature_icon_alter_statistic_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyfeature',
            name='title',
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('appetizers', 'Закуски'), ('soups', 'Супы'), ('main', 'Горячее'), ('desserts', 'Десерты'), ('drinks', 'Напитки')], max_length=20, verbose_name='Категория блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='dish_images/', verbose_name='Изображение блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новое'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярное'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название блюда'),
        ),
    ]
