# Generated by Django 6.0.3 on 2026-04-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_category_historyfeature_title_alter_dish_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория блюд', 'verbose_name_plural': 'Категории блюд'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='working_hours',
            field=models.TextField(max_length=500, verbose_name='Часы работы'),
        ),
    ]
