# Generated by Django 6.0.3 on 2026-04-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Используется для фильтрации. Заполняется автоматически из названия (латиницей).', max_length=100, unique=True, verbose_name='Slug (для фильтра на сайте)'),
        ),
    ]
