# Generated by Django 6.0.3 on 2026-04-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Фото клиента')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Рейтинг (1-5)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Отображать на главной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
