# Generated by Django 6.0.3 on 2026-04-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0023_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('completed', 'Завершено')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
