# Generated by Django 6.0.3 on 2026-04-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_contactmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
