# Generated by Django 6.0.3 on 2026-04-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0025_reservation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '6) Категории меню', 'verbose_name_plural': '6) Категории меню'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': '10) Сообщения', 'verbose_name_plural': '10) Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': '7) Блюда', 'verbose_name_plural': '7) Блюда'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': '8) Галерея', 'verbose_name_plural': '8) Галерея'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': '4) Новости', 'verbose_name_plural': '4) Новости'},
        ),
        migrations.AlterModelOptions(
            name='ourhistory',
            options={'verbose_name': '2) История', 'verbose_name_plural': '2) История'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '9) Бронирования', 'verbose_name_plural': '9) Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': '1) Настройки', 'verbose_name_plural': '1) Настройки'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': '3) Статистика', 'verbose_name_plural': '3) Статистика'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': '5) Отзывы', 'verbose_name_plural': '5) Отзывы'},
        ),
    ]
