# Generated by Django 6.0.3 on 2026-04-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0026_alter_category_options_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '06) Категории', 'verbose_name_plural': '06) Категории'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': '07) Блюда', 'verbose_name_plural': '07) Блюда'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': '08) Галерея', 'verbose_name_plural': '08) Галерея'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': '04) Новости', 'verbose_name_plural': '04) Новости'},
        ),
        migrations.AlterModelOptions(
            name='ourhistory',
            options={'verbose_name': '02) История', 'verbose_name_plural': '02) История'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '09) Бронирования', 'verbose_name_plural': '09) Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': '01) Настройки', 'verbose_name_plural': '01) Настройки'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': '03) Статистика', 'verbose_name_plural': '03) Статистика'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': '05) Отзывы', 'verbose_name_plural': '05) Отзывы'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='map_link',
            field=models.TextField(help_text='Используйте только атрибут src из кода вставки Google Maps (начинается с https://www.google.com/maps/embed...)', verbose_name='Ссылка на карту (iframe src)'),
        ),
    ]
