# Generated by Django 6.0.3 on 2026-04-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0027_alter_category_options_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': '01) Основные настройки', 'verbose_name_plural': '01) Основные настройки'},
        ),
    ]
