# Generated by Django 6.0.3 on 2026-04-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_alter_settings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер для доставки'),
        ),
    ]
