# Generated by Django 6.0.3 on 2026-04-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0029_settings_delivery_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка на WhatsApp'),
        ),
    ]
