# Generated by Django 6.0.3 on 2026-04-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_settings_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='whatsapp',
            field=models.CharField(blank=True, help_text="Введите номер без '+' и пробелов, например: 996555212293", max_length=250, null=True, verbose_name='Номер WhatsApp'),
        ),
    ]
