# Generated by Django 6.0.3 on 2026-04-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0031_alter_settings_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyfeature',
            name='icon',
            field=models.CharField(help_text='Для обычных: fa-solid fa-leaf. Для брендов: fa-brands fa-bluetooth. Поиск free иконок на fontawesome.com', max_length=100, verbose_name='Иконка (FontAwesome)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon',
            field=models.CharField(help_text='Используйте fa-solid для обычных иконок (напр. fa-solid fa-bowl-food) или fa-brands для соцсетей. Поиск: fontawesome.com/search?m=free', max_length=100, verbose_name='Иконка (FontAwesome класс)'),
        ),
    ]
