# Generated by Django 6.0.3 on 2026-04-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0032_alter_historyfeature_icon_alter_statistic_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Фон главного экрана'),
        ),
    ]
