# Generated by Django 6.0.3 on 2026-04-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0033_settings_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='dish',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена по акции'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_promotion',
            field=models.BooleanField(default=False, verbose_name='Акция'),
        ),
        migrations.AddField(
            model_name='dish',
            name='promotion_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания акции'),
        ),
    ]
