# Generated by Django 6.0.3 on 2026-04-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0034_dish_discount_percent_dish_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Логотип сайта'),
        ),
    ]
