# Generated by Django 6.0.3 on 2026-04-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0035_settings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя повара')),
                ('title', models.CharField(max_length=100, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Краткое описание/Биография')),
                ('image', models.ImageField(upload_to='chefs/', verbose_name='Фото повара')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше повар в списке', verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Повар',
                'verbose_name_plural': 'Повара',
                'ordering': ['order'],
            },
        ),
    ]
