# Generated by Django 6.0.3 on 2026-04-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0036_chef'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chef',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='discount_percent',
        ),
    ]
