# Generated by Django 6.0.3 on 2026-04-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0037_delete_chef_remove_dish_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя повара')),
                ('title', models.CharField(max_length=100, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='chefs/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '11) Повара',
                'verbose_name_plural': '11) Повара',
            },
        ),
    ]
