# Generated by Django 6.0.3 on 2026-04-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0038_chef'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chef',
        ),
        migrations.AddField(
            model_name='news',
            name='promotion_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания акции'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Описание новости'),
        ),
    ]
