# Generated by Django 6.0.3 on 2026-04-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0039_delete_chef_news_promotion_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='new_until_date',
            field=models.DateField(blank=True, help_text="Блюдо будет отображаться как 'Новое' до этой даты.", null=True, verbose_name='Новое до даты'),
        ),
    ]
