# Generated by Django 6.0.3 on 2026-05-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0040_dish_new_until_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название блюда'),
        ),
    ]
