# Generated by Django 6.0.3 on 2026-05-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0041_alter_dish_description_alter_dish_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной странице'),
        ),
    ]
