# Generated by Django 6.0.3 on 2026-05-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0042_alter_dish_is_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
    ]
