# Generated by Django 6.0.3 on 2026-05-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0043_remove_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Изображение для иконки сайта (например, .ico, .png). Рекомендуется 32x32 или 64x64 пикселя.', null=True, upload_to='settings/', verbose_name='Фавикон (иконка сайта)'),
        ),
    ]
